version: '3.7'
services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./db:/usr/src/db
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - '80:3000'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
      - mongo

  mongo:
    container_name: mongodb
    image: mongo:4.2.0-bionic
    restart: always
    expose:
      - '27017'
    volumes:
      - ./db:/data/db

  adminMongo:
    container_name: adminMongo
    image: mrvautin/adminmongo
    ports:
      - '1234:1234'
    environment:
      - HOST=0.0.0.0
      - DB_HOST=mongo
      - CONN_NAME=adminMongo
      - DB_NAME=CentrosCulturales
    depends_on:
      - mongo
