version: '3.7'
services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongo
  
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - '80:3000'
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
      - mongo

  mongo:
    container_name: mongodb
    image: mongo:4.2.0-bionic
    expose:
      - '27017'